language: java

before_install:
- cp .travis.settings.xml $HOME/.m2/settings.xml

jdk:
  - openjdk11

cache:
  directories:
  - $HOME/.m2/repository/

script:
-  mvn -e verify deploy

env:
- SPRING_PROFILES_ACTIVE=ci

